placesToVisit = ["Manali", "Leh Ladakh", "Coorg", "Andaman", "Laskwadeep"]

print(placesToVisit)
print(sorted(placesToVisit))
print(placesToVisit)
print(sorted(placesToVisit, reverse=True))
print(placesToVisit)
placesToVisit.reverse()
print(placesToVisit)
placesToVisit.reverse()
print(placesToVisit)
placesToVisit.sort()
print(placesToVisit)
placesToVisit.sort(reverse=True)
print(placesToVisit)
